import { styled } from '@/stitches.config';
import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';

import { getCharacters, getEpisodes, getLocations } from 'rickmortyapi';

import Gallery from '@/components/Gallery';
import Header from '@/components/Header';
import Separator from '@/components/Separator';
import { FormEvent, useState } from 'react';
import type { Character, Episode, Location } from 'rickmortyapi/dist/interfaces';

const Section = styled('section', {
    position: 'relative',

    backgroundImage: "url('/assets/images/rick-morty.png')",
    backgroundRepeat: 'no-repeat',
    backgroundSize: 'cover',
    marginX: '12%',
    paddingBottom: '65%',
    height: 0,
    textAlign: 'center'
});

export const getStaticProps: GetStaticProps = async () => {
    const characters = await getCharacters();
    const locations = await getLocations();
    const episodes = await getEpisodes();

    return {
        props: {
            characters: characters.data.results,
            locations: locations.data.results,
            episodes: episodes.data.results
        }
    };
};

const Search = styled('input', {
    border: '1px solid $gray6',
    fontSize: 16,
    borderRadius: 6,
    padding: 12
});
interface Props {
    characters: Character[];
    locations: Location[];
    episodes: Episode[];
}

const Home: NextPage<Props> = ({ ...props }: Props) => {
    const [search, setSearch] = useState<string>('');

    const handleSearch = (event: FormEvent<HTMLInputElement>) => {
        event.preventDefault();
        if (!search.length) return;

        setSearch('');
    };

    return (
        <>
            <Head>
                <title>Rick & Morty</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Header />
                <Section>
                    <Search
                        placeholder="Search.."
                        type="search"
                        value={search}
                        onChange={(e) => setSearch(e.target.value)}
                        onSubmit={(e) => handleSearch(e)}
                    />
                </Section>
                <Separator css={{ marginTop: 0 }} />

                <section>
                    <h1 style={{ textAlign: 'center' }}>Gallery</h1>
                    <Gallery initialProps={props} />
                </section>
            </main>
        </>
    );
};

export default Home;
