import { styled } from '@/stitches.config';
import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';

import { getCharacters, getEpisodes, getLocations } from 'rickmortyapi';

import Gallery from '@/components/Gallery';
import Header from '@/components/Header';
import Separator from '@/components/Separator';
import MagnifyingGlass from '@/components/svgs/MagnifyingGlass';
import { useRouter } from 'next/router';
import { FormEvent, useState } from 'react';
import type { Character, Episode, Location } from 'rickmortyapi/dist/interfaces';

const Section = styled('section', {
    position: 'relative',
    display: 'flex',
    justifyContent: 'center',

    backgroundImage: "url('/assets/images/rick-morty.png')",
    backgroundRepeat: 'no-repeat',
    backgroundSize: 'cover',
    marginX: '12%',
    paddingBottom: '65%',
    height: 0,
    textAlign: 'center'
});

export const getStaticProps: GetStaticProps = async () => {
    const characters = await getCharacters();
    const locations = await getLocations();
    const episodes = await getEpisodes();

    return {
        props: {
            characters: characters.data.results,
            locations: locations.data.results,
            episodes: episodes.data.results
        }
    };
};

const Form = styled('form', {
    backgroundColor: '#fff',
    display: 'flex',
    alignItems: 'center',
    padding: '20px 12px',
    border: '1px solid $gray4',
    borderRadius: 6,

    variants: {
        focus: {
            true: {
                outline: '1.5px solid black'
            },
            false: {
                outline: 'none'
            }
        }
    }
});

const Search = styled('input', {
    fontSize: 16,
    padding: 8,
    border: 'none',
    marginLeft: 4,
    '&:focus': {
        outline: 'none'
    }
});
interface Props {
    characters: Character[];
    locations: Location[];
    episodes: Episode[];
}

const Home: NextPage<Props> = ({ ...props }: Props) => {
    const [loading, setLoading] = useState<boolean>(false);
    const [search, setSearch] = useState<string>('');
    const [focus, setFocus] = useState<boolean>(false);
    const router = useRouter();

    const handleSearch = async (event: FormEvent<HTMLFormElement>) => {
        event.preventDefault();
        if (!search.length) return;

        router.push(`/search?text=${search}`);
    };

    return (
        <>
            <Head>
                <title>Rick & Morty</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Header />
                <Section>
                    <Form onSubmit={(e) => handleSearch(e)} focus={focus}>
                        <MagnifyingGlass />
                        <Search
                            placeholder="Search.."
                            type="search"
                            value={search}
                            onChange={(e) => setSearch(e.target.value)}
                            onFocus={() => setFocus(true)}
                            onBlur={() => setFocus(false)}
                        />
                    </Form>
                </Section>
                <Separator css={{ marginTop: 0 }} />

                <section>
                    <h1 style={{ textAlign: 'center' }}>Gallery</h1>
                    <Gallery initialProps={props} />
                </section>
            </main>
        </>
    );
};

export default Home;
