import { styled } from '@/stitches.config';
import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

import { getCharacters, getEpisodes, getLocations } from 'rickmortyapi';

import Gallery from '@/components/Gallery';
import Separator from '@/components/Separator';
import type { Character, Episode, Location } from 'rickmortyapi/dist/interfaces';

const Header = styled('header', {
    display: 'flex',
    justifyContent: 'center',
    padding: 16
});

const Section = styled('section', {
    position: 'relative',

    backgroundImage: "url('/assets/images/rick-morty.png')",
    backgroundRepeat: 'no-repeat',
    backgroundSize: 'cover',
    marginX: '12%',
    paddingBottom: '65%',
    height: 0,
    textAlign: 'center'
});

export const getStaticProps: GetStaticProps = async () => {
    const characters = await getCharacters();
    const locations = await getLocations();
    const episodes = await getEpisodes();

    return {
        props: {
            characters: characters.data.results,
            locations: locations.data.results,
            episodes: episodes.data.results
        }
    };
};

interface Props {
    characters: Character[];
    locations: Location[];
    episodes: Episode[];
}

const Home: NextPage<Props> = ({ ...props }: Props) => {
    return (
        <>
            <Head>
                <title>Rick & Morty</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Header>
                    <Image
                        src="/assets/images/header.png"
                        alt="Rick and Morty text logo"
                        width={400}
                        height={100}
                    />
                </Header>
                <Section />
                <Separator css={{ marginTop: 0 }} />
                <section>
                    <h1 style={{ textAlign: 'center' }}>Gallery</h1>
                    <Gallery initialProps={props} />
                </section>
            </main>
        </>
    );
};

export default Home;
